### ISSUE TITLE
Płatność w innej walucie - ApiException

### ISSUE THREAD

**Issue by patryk-uszynski** [dotpay/PrestaShop-1.7.x#10]
Udało mi się obejść problem z #5, jednak przechodząc dalej otrzymuje taki błąd:
```
ApiException in Payment.php line 53:
Required parameters not present, required parameters "id, amount, currency"
```
Dzieje się tak tylko w przypadku innych walut niż PLN

**Comment by patryk-uszynski** [comment]
Duplikat #9, jednak dalej nierozwiązany. Najlepiej byłoby dać `round` w `controllers\front\dotpay.php`
```
$orderAmount = \Tools::convertPrice($orderAmount, $currency["id_currency"], false);
$orderAmount = round($orderAmount, 2);
```

**Comment by patryk-uszynski** [comment]
Właściwie ten `Tools::convertPrice` przeliczna ceny na walutę domyślną (u mnie na zł), po czym dotpay robi to ponownie i cena się nie zgadza. Lepiej go wyrzucić i zostawić tylko `round`

**Comment by tbajorek** [comment]
Proszę sprawdzić, czy najnowsza wersja jest pozbawiona tego błędu. Usunęliśmy wspomnianą linijkę.
[https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.7](https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.7)
