### ISSUE TITLE
StreetException in Customer.php line 187:

### ISSUE THREAD

**Issue by 2404pawel** [dotpay/PrestaShop-1.7.x#12]
Wtyczka nie obsługuje polskich znaków. Załączam screena. Po usunięciu polskiego znaku płatność jest OK.
![dotpay](https://user-images.githubusercontent.com/33042518/31915749-f53f0110-b84f-11e7-9f96-5a59da8289ca.JPG)

**Comment by 2404pawel** [comment]
Ten akurat problem rozwiązałem zmieniając regexpa na
    public static function validate($value) {
        // return (bool)preg_match('/^[\p{L}0-9\.\s\-\/]{2,100}$/', $value); tak było
        return (bool)preg_match('/^[a-zA-zĄąĆćĘęŁłŃńÓóŚśŹźŻż0-9\.\s\-\/]{2,100}$/', $value);
    }

Wydaje się więc że do zamknięcia temat. Otwieram jednak inne, ponieważ występują poważne błędy

**Comment by wpawel** [comment]
proszę sprawdzić najnowszą wersję [1.0.8](https://github.com/dotpay/PrestaShop-1.7.x/tree/v1.0.8)

**Comment by wpawel** [comment]
Problem z walidacją ulicy występował w wersji 1.0.7 . Przy włączonej opcji DEBUG w PrestaShop pojawiały sie również inne problemy. Usunięto je w najnowszym wydaniu [v1.0.8.1](https://github.com/dotpay/PrestaShop-1.7.x/tree/v1.0.8.1).
