### ISSUE TITLE
Brak automatycznego potwierdzenia

### ISSUE THREAD

**Issue by 2404pawel** [dotpay/PrestaShop-1.7.x#13]
Czy wtyczka nie powinna wysyłać automatycznego powiadomienia o przyjęciu płatności? Na koncie testowym płatność jest oznaczona jako "wykonana" jednak w sklepie internetowym brak jest zmiany statusu:
![image](https://user-images.githubusercontent.com/33042518/31917067-fd6c60b6-b855-11e7-8ca7-889cecee7df6.png)

Pozdrawiam,
Paweł

**Comment by wpawel** [comment]
Aby otrzymać notyfikację z Dotpay, serwer gdzie zainstalowano sklep musi być dostępny dla serwera Dotpay, w tym wypadku tak nie było:  "503 Server Error: Service Unavailable" . Taką informację można sprawdzić w logach transakcji zainicjowanej w panelu Dotpay w szczegółach transakcji.
