### ISSUE TITLE
Błąd "szczegóły transakcji"

### ISSUE THREAD

**Issue by 2404pawel** [dotpay/PrestaShop-1.7.x#14]
Po wybraniu przycisku "Details" w panelu klienta w sklepie internetowym otrzymuję poniższy błąd:
![image](https://user-images.githubusercontent.com/33042518/31917123-34c1b386-b856-11e7-8aba-5830449b06e9.png)

Gdy wybieram tę opcję dla transakcji niezrealizowanej przy pomocy dotpay, błędu nie ma.

Pozdrawiam,
Paweł

**Comment by wpawel** [comment]
proszę zainstalować najnowsza wersje v1.0.8 oraz wyczyścić pamięć podręczną PrestaShop

**Comment by wpawel** [comment]
Problem występował przy właczonej opcji DEBUG w PrestaShop. Usunięto go w najnowszym wydaniu [v1.0.8.1](https://github.com/dotpay/PrestaShop-1.7.x/tree/v1.0.8.1).
