### ISSUE TITLE
Presta 1.7.0.4 nie widzi dotpay 1.0.7

### ISSUE THREAD

**Issue by tomekdpl** [dotpay/PrestaShop-1.7.x#15]
Cześć
Niestety sklep musickeys.pl nie widzi płatności dotpay 1.0.7 
Czy jesteście w stanie pomóc ?

**Comment by mateuszpy** [comment]
Przyczyną problemu są obecne na serwerze pozostałości po starym module, przeznaczonym jeszcze pod wersję 1.6.
Proszę odinstalować obecną wersję wtyczki i na serwerze usunąć cały folder Dotpay z katalogu modułów, powinno to rozwiązać problem.
