### ISSUE TITLE
Dotpay\Exception\Resource\Channel\NotFoundException

### ISSUE THREAD

**Issue by tannerpl** [dotpay/PrestaShop-1.7.x#16]
Zainstalowałem i skonfigurowałem moduł dotpay na presatshop 1.7. Płatność dotpay jednak nie pojawia się w checkoucie. Przy każdym jego kroku natomiast widoczna jest linijka tekstu: "Dotpay\Exception\Resource\Channel\NotFoundException".  Załączam screenshot. 
![dotpay](https://user-images.githubusercontent.com/33556726/32675345-e477219a-c656-11e7-9f64-87fb8235fae6.png)

**Comment by wpawel** [comment]
W sklepie użyto dodatkowego modułu zmieniającego standardowy wygląd koszyka (coś w stylu: One Page Checkout ), Moduł płatności Dotpay nie był testowany przez nas z komercyjnymi rozwiązaniami tego typu i nie możemy zagwarantować poprawnej współpracy ze wszystkimi tego typu dodatkami.

Proszę zweryfikować czy w konfiguracji wtyczki płatności Dotpay zostały wyłączone dodatkowe opcje jak: 'Pokaż kanały płatności na stronie sklepu ', 'Włącz osobno kanał Blik', 'Włącz osobno kanał kart płatniczych' oraz 'Włącz płatności kartowe One Click' oraz nie korzystać z funkcji: 'Wyodrębnione kanały na stronie sklepu'.
Jeśli powyższe nie pomoże, proszę o włączenie trybu DEBUG dla PrestaShop i weryfikację czy pokażą się dodatkowe komunikaty błędów.
Szczegóły proszę zgłosić bezpośrednio na adres: tech@dotpay.pl podając również wersje użytej PrestaShop, wersji modułu Dotpay, PHP oraz nazwy i wersji modułu dodatkowego który modyfikuje wygląd standardowego koszyka.
