### ISSUE TITLE
Pojawianie się Maila użytkownika na podstronie Zamówienie

### ISSUE THREAD

**Issue by BPHagrid** [dotpay/PrestaShop-1.7.x#17]
Witam,
Po zainstalowaniu wtyczki DotPay, zauważyłem, że na stronie Zamówienia, pojawia się mail użytkownika (bądź też "Customer id" jak jest niezalogowany).
Zainstalowana najnowsza wersja modułu.
![blad-dotpay](https://user-images.githubusercontent.com/34743580/34257490-625f5ee2-e65a-11e7-8766-8a9b4419a94d.jpg)
A tutaj po wyłączeniu modułu.
![blad-dotpay-wylaczone](https://user-images.githubusercontent.com/34743580/34257491-627dcdb4-e65a-11e7-8c84-ff16a1725975.jpg)

**Comment by wpawel** [comment]
komunikat został wyłączony w ostatniej wersji modułu : [v1.0.8.3](https://github.com/dotpay/PrestaShop-1.7.x/tree/v1.0.8.3)

**Comment by BPHagrid** [comment]
Zainstalowany został najnowszy moduł v1.0.8.4 i wciąż się pojawia "Customer id" (ew. mail użytkownika)
