### ISSUE TITLE
Problem z instalacją dotpay

### ISSUE THREAD

**Issue by universalnick** [dotpay/PrestaShop-1.7.x#21]
WItam, pracuję na prestashop 1.7.1.2 PHP 5.4.45 czyli teoretycznie wymagania dla modułu dotpay  1.0.9 spełnione, jednak po pobraniu modułu nie udało się go zainstalować.
Informacja o błędzie:
[Wed Feb 07 21:43:39 2018] [error] [client 94.254.238.75] PHP Fatal error:  Can't use method return value in write context in /var/www/xxxxx/modules/dotpay/sdk/Dotpay/Loader/Loader.php on line 250, referer: 

Jak można to rozwiązać i zainstalować poprawnie moduł?

**Comment by wpawel** [comment]
Proszę zmienić wersje PHP na : Wersja PHP: 7.0.x, powinno pomóc.

**Comment by universalnick** [comment]
Witam serdecznie,

Dziękuje za odpowiedź.

Niestety nie mam możliwości zmiany php na 7.0.x

Czy jest inna możliwość rozwiązania problemu?

Oraz pytanie brzmi dlaczego w takim razie jest informacja że przy PHP 5.4 moduł jest kompatybilny?

 

Z góry dziękuje za odpowiedź i pozdrawiam,

 

  _____  

  Milena Józefowicz
  ASYSTENTKA DS. MARKETINGU I SPRZEDAŻY
 <http://www.jubiler.art.pl/> cid:image001.gif@01D27C8A.D2C08890
  PHU Jubiler Sp. z o.o.
  02-822 Warszawa
  ul. Poleczki 13
   <mailto:milena.jozefowicz@jubiler.art.pl> milena.jozefowicz@jubiler.art.pl

**Comment by wpawel** [comment]
Moduł działa poprawnie od wersji PHP >=5.6.
Informacja o starszej wersji PHP 5.4 była obecna w pierwszej wersji instrukcji  co zostało poprawione,
W ostatniej wersji modułu [v1.0.9.1](https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.9.1)  poprawiono współpracę z wersją 5.6, oraz dodano zaktualizowaną instrukcję do modułu.
Informacja o współpracy z wersja php >=5.6 pojawiła się w module od wersji [v1.0.8](https://github.com/dotpay/PrestaShop-1.7.x/blob/v1.0.8/dotpay.php#L248)
