### ISSUE TITLE
Tworzenie zamówienia na sklepie przed zakończeniem płatności

### ISSUE THREAD

**Issue by BPHagrid** [dotpay/PrestaShop-1.7.x#22]
Witam,
Czy jest możliwość zmiany funkcjonalności modułu, by tworzył zamówienie na sklepie dopiero po tym, jak płatność zostanie poprawnie wykonana?
Bo aktualnie jest to robione, gdy przechodzimy do strony płatności i gdy klient, wróci się na stronę sklepu, to koszyk jest pusty.

**Comment by wpawel** [comment]
Zapewne jest możliwe ale zgodnie z oczekiwaniami użytkowników modułu płatności preferowany jest właśnie taki model kiedy po inicjacji płatności tworzone jest zamówienie w sklepie. Jedna ze starszych wersji wtyczki działała w takim modelu kiedy zamówienie było tworzone po udanej płatności, ale taka wersja się nie sprawdziła dlatego zostało to zmienione.
Zalogowany klient sklepu ma możliwość ponowienie płatności lub zamówienia ponieważ zapisywana jest jego historia zamówień. 
Problem zatem może dotyczyć niezalogowanego klienta. Dla zainicjowanych i niedokończonych  transakcji jest możliwość by płacący otrzymał w mailu link do dokończenia płatności (wysyłany po ok 15 minut od inicjacji płatności). W Dotpay można poprosić o włączenie takiej funkcjonalności dla konkretnego konta.
