### ISSUE TITLE
Ponowienie płatności błąd w historii zamówienia

### ISSUE THREAD

**Issue by preska24** [dotpay/PrestaShop-1.7.x#23]
Po zainstalowaniu modułu na prestashop 1.7, w historii  zamówień w szczegółach zamówienia, wyświetla się ten kod zamiast opcji ponowienie płatności 

`<div class="box" style="overflow: auto;"> <h2 class="page-subheading"><a href="http://www.dotpay.pl" target="_blank" title="www.dotpay.pl"><img id="dotpay-logo" src="/modules/dotpay/views/img/dotpay_logo_big.png" alt="Dotpay - Szybkie i bezpieczne płatności internetowe"/></a>&nbsp;Płać łatwo z Dotpay</h2> <p>Twoja płatność nie została jeszcze potwierdzona przez Dotpay. Jeżeli ją przerwałeś, możesz ją powtórzyć.</p> <p class="cart_navigation"> <a class="btn btn-info" href="https://preska.pl/pl/module/dotpay/renew?order_id=10"> <span id="proceedPaymentLink"> Ponów płatność </span> </a> </p> </div>`

**Comment by kris4net** [comment]
u mnie kliknięcie w pomów płatność nie robi nic tylko przenosi na stronę główną.
brak błędu w devmode presta 1.7.3.2 dotpay 1.0.9.2a.

**Comment by wpawel** [comment]
Proszę o pobranie najnowszej wersji wtyczki: [v1.1.0](https://github.com/dotpay/PrestaShop-1.7.x/tree/v1.1.0) , tam problem nie powinien występować.
