### ISSUE TITLE
Uncheck the agreement checkbox by default

### ISSUE THREAD

**Issue by bandi007** [dotpay/PrestaShop-1.7.x#25]
Due to the GDPR regulations agreement checkbox should not be checked by default.

**Comment by wpawel** [comment]
Consent can be treated as a true consent only when it is fully voluntary and cancellable. Without the acceptance of regulations and consent for processing of personal data of buyer Dotpay is unable to deliver payment service. This is the sole reason that the checkbox indicating acceptance of Regulations is selected, which is fully compatible with current law regulations.
