### ISSUE TITLE
Błąd przy php 7.2

### ISSUE THREAD

**Issue by iqit-commerce** [dotpay/PrestaShop-1.7.x#27]
Compile Error: Cannot use Dotpay\Loader\Xml\Object as Object because 'Object' is a special class name

in modules/dotpay/sdk/Dotpay/Loader/Loader.php (line 22)
 */namespace Dotpay\Loader;use \ReflectionClass;use Dotpay\Loader\Xml\Param;use Dotpay\Loader\Xml\Object;

**Comment by wpawel** [comment]
zmienione w [v1.1.3](https://github.com/dotpay/PrestaShop-1.7.x/tree/v1.1.3)
