### ISSUE TITLE
Globalne klasy css

### ISSUE THREAD

**Issue by iqit-commerce** [dotpay/PrestaShop-1.7.x#28]
W raz z modułem dotpay łądowany jest plik
https://ssl.dotpay.pl/t2/widget/payment_widget.min.css

zawiera on takie klasy jak

.loading lub .selected i podobne które nie są poprzedzone klasa/id powiązana  z dotpayem przez co maja wpływ na ogólny wygląd sklepu

**Comment by wpawel** [comment]
zmienione w [v1.1.3](https://github.com/dotpay/PrestaShop-1.7.x/tree/v1.1.3)
