### ISSUE TITLE
Błąd PHP podczas instalacji 1.0.4 na Presta 1.7.1.2 

### ISSUE THREAD

**Issue by hittg** [dotpay/PrestaShop-1.7.x#4]
Błąd w logach Apache:

PHP Fatal error:  Can't use method return value in write context in (...)\\modules\\dotpay\\sdk\\Dotpay\\Loader\\Loader.php on line 215, referer: (...)/index.php/module/manage?token=9cd4470cfdc1f6b93eb1ded17cac0d09

**Comment by tbajorek** [comment]
Jaka jest używana w Pańskim sklepie wersja PHP? Rekomendowaną wersją dla poprawnego działania naszej wtyczki jest minimum 5.4. Ewnetualnie wyższa.

**Comment by hittg** [comment]
Na serwerze jest wersja 5.4.37

**Comment by hittg** [comment]
problem dopiero zniknął na wersji PHP 5.6
