### ISSUE TITLE
Lista controllerów

### ISSUE THREAD

**Issue by Faliszek** [dotpay/PrestaShop-1.7.x#6]
W metodzie __construct nalezy wprowadzić listę kontrollerów żeby działały poprawnie po instalacji modułu

```
$this->controllers = array('back', 'confirm', 'dotpay', 'instruction', 'ocmanage', 'ocremove', 'preparing', 'renew', 'status');
```

**Comment by tbajorek** [comment]
Twórcy Prestashop nie dają już listy kontrolerów do swoich własnych wtyczek, więc nie wiem, czy to jest potrzebne. Np. [https://github.com/PrestaShop/paypal/blob/master/paypal.php#L95](https://github.com/PrestaShop/paypal/blob/master/paypal.php#L95)
