### ISSUE TITLE
Niepotrzebne przeliczanie waluty

### ISSUE THREAD

**Issue by jedzura** [dotpay/PrestaShop-1.7.x#8]
Mam w swoim sklepie dwie waluty - euro i złotówki, jako główna waluta ustawione jest euro, gdy chcę dokonać płatności przez dotpay w złotówkach to pokazuje mi ładnie na stronie cenę w złotówkach, ale jak przechodzę do strony płatności w banku lub kartą to ta cena zostaje podzielona przez aktualnie ustawiony kurs euro i w efekcie klient może zapłacić kilkukrotnie mniej niż powinien :(

**Comment by jedzura** [comment]
Nie doczekałem się odpowiedzi, więc dla potomnych, gdyby ktoś miał taki sam błąd to niech wywali linijkę numer 103 z pliku dotpay/controllers/front/dotpay.php o treści: "$orderAmount = \Tools::convertPrice($orderAmount, $currency["id_currency"], false);"
W tej linijce zachodzi bardzo dziwne przewalutowanie, po jej wywaleniu wszystko działa cacy :)

**Comment by tbajorek** [comment]
Proszę sprawdzić, czy najnowsza wersja jest pozbawiona tego błędu. Usunęliśmy wspomnianą linijkę.

**Comment by tbajorek** [comment]
Proszę sprawdzić, czy najnowsza wersja jest pozbawiona tego błędu. Usunęliśmy wspomnianą linijkę.
[https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.7](https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.7)
